add support for loongarch
kernelslacker/trinity pull request #46
Opened 2023-09-18 07:25 UTC by wuruilong01

2023-09-24 16:58 UTC, kernelslacker requested changes
loongarch bits look ok, the other bits should be broken out, with separate explanations/commits.

2023-09-24 16:58 UTC, kernelslacker commented on ioctls/autofs.c
this part should be a separate diff.

2023-09-24 16:58 UTC, kernelslacker commented on ioctls/scsi.c
separate diff.

2023-09-24 16:58 UTC, kernelslacker commented on syscalls/vmsplice.c
separate diff, and some explanation why ?

2023-09-24 16:58 UTC, kernelslacker commented on sysv-shm.c
separate diff too.

2023-09-25 01:43 UTC, wuruilong01 commented
Other files have been fixed for bugs caused by SEGV and tested on LoongArch.

- the used address to fill data should exist,otherwise trinity may get SEGV signal.
- arg3type of vmsplice is ARG_IOVECLEN,if you modify it,you should also modify arg2 accordingly.

Sorry, I'm a beginner; perhaps fixing the errors should be done in the next submission.

2026-07-17 16:37 UTC, closed without merging